version: '3'
services:
  vue:
    container_name: front-web
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './vue.conf:/etc/nginx/conf.d/vue.conf'
    ports:
      - "8080:80"

